CXX			= c++
CXXFLAGS	= -Wall -Wextra -Werror -std=c++98

NAME	= exe
SRCS	= megaphone.cpp
OBJS	= ${SRCS:%.cpp=%.o}

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

all: $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
